entrada = input()

print(" _", end='')
print("_"*(len(entrada)+1))
print(f"< {entrada} >")
print(" =", end='')
print("="*(len(entrada)+1))
print("        \\   ^..^      /")
print("         \\  /_/\\_____/")
print("               /\\   /\\")
print("              /  \\ /  \\")